const trying = () =>{
    d = 2
        if (d===2){
          return  console.log('true')
            
        }
        throw new Error = ('wrong')
        console.log(error.message)
    // catch{
    //     console.log(false)
    // }
}

trying();